In [1]:
**задание 1**

SyntaxError: invalid syntax (<ipython-input-1-69f8d7168965>, line 1)

In [ ]:
from matplotlib import pyplot as plt
import pandas as pd
%matplotlib inline
%config InlineBackend.figure_format = 'svg'
x = [1, 2, 3, 4, 5, 6, 7]
y = [3.5, 3.8, 4.2, 4.5, 5, 5.5, 7]
plt.plot(x,y)
plt.show()
plt.scatter(x,y)
plt.show()

In [ ]:
**задание 2**

In [ ]:
t = np.linspace(0, 10, 51)
print(t)
f=np.cos(t)
print(f)
plt.plot(t, f, color="green")
plt.axis([0.5, 9.5, -2.5, 2.5])
plt.title('График f(t)', fontdict=title_font)
plt.xlabel('Значения t', fontdict=label_font)
plt.ylabel('Значения f')
plt.show()


In [ ]:
**задание 3**

In [ ]:
x = np.linspace(-3, 3, 51)
print(t)
y1 = x**2
y2 = 2*x + 0.5
y3 = -3*x - 1.5
y4 = np.sin(x)

fig, ax = plt.subplots(nrows=2, ncols=2)
ax1, ax2, ax3, ax4 = ax.flatten()
ax1.plot(x, y1)
ax1.set_title('График y1')
ax1.set_xlim([-5, 5])
ax2.plot(x, y2)
ax2.set_title('График y2')
ax3.plot(x, y3)
ax3.set_title('График y3')
ax4.plot(x, y4)
ax4.set_title('График y4')
fig.set_size_inches(8, 6)
plt.subplots_adjust(wspace=0.3, hspace=0.3)
#plt.show()

In [ ]:
**задание 3**

In [ ]:
plt.style.use('fivethirtyeight')
DATASET_PATH = './creditcard.csv'
df = pd.read_csv(DATASET_PATH, sep=',')
df.head()
t = df['Class'].value_counts()
t

df_class = pd.Series(t)
df_class.plot(kind='bar')
plt.show()
df_class.plot(kind='bar', logy=True)
plt.show()

v1_class1=df.set_index('Class')['V1'].filter(like='1', axis=0)
v1_class1=v1_class1.reset_index()
v1_class1=v1_class1.drop('Class', axis=1)
v1_class1.head()
v1_class1.count()
v1_class0=df.set_index('Class')['V1'].filter(like='0', axis=0)
v1_class0=v1_class0.reset_index()
v1_class0=v1_class0.drop('Class', axis=1)
v1_class0.head()
v1_class0.count()

plt.hist(v1_class0['V1'], bins=20, color='grey', edgecolor='black', density = True, orientation='horizontal')
plt.hist(v1_class1['V1'], bins=20, color='red', edgecolor='black', density = True, orientation='horizontal')
plt.plot()
plt.xlabel('Class')
plt.legend(labels=['Class 0', 'Class 1'])

In [ ]:
**Задание на повторение материала**

In [ ]:
import numpy as np
a = np.arange(12,24)
print(a)
a1=a.reshape(6, 2)
a2=a.reshape(2, 6)
a3=a.reshape(3, 4)
a4=a.reshape(4, 3)
a5=a.reshape(12, 1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
a6=a.reshape(6, -1)
a7=a.reshape(2, -1)
a8=a.reshape(3, -1)
a9=a.reshape(-1, 3)
a11=a.reshape(-1, 1)
print(a6)
print(a7)
print(a8)
print(a9)
print(a11)
#Если в массиве для обращения к элементам используется
# только один порядковый номер, то такой массив
# называется линейным, или одномерным. Одномерный
# массив можно представить в виде таблицы, в которой
# существует только одна строка.

In [ ]:
b=np.random.randn(3,4)
print(b)
print("размер исходного массива: {}".format(b.size))
b1=b.flatten()
print(b1)
print("размер одномерного массива: {}".format(b1.size))

In [ ]:
a=np.arange(20, 0, -2)
print("одномерный массив \n", a)
b=np.arange(20, 1, -2)
b1=b.reshape(1, 10)
print("двумерный массив \n", b1)

In [ ]:
a = np.zeros((2, 2))
b = np.zeros((3, 2))+1
v = np.vstack((a, b))
print("размер массива v: {}".format(v.size))
print(v)

In [20]:
a=np.arange(0, 12)
A=a.reshape(4,3)
At=A.T
B = np.dot(A, At)
print("размер массива B {}".format(B.size))
print(B) # обратной матрицы не получится
print(A) #вырожденная матрица

#np.random.seed(42)
c = np.random.randint(0, 16, 16)
print(c)
C = c.reshape(4,4)
print(c)
d = B + C*10
print(d)
det = np.linalg.det(d)
rank = np.linalg.matrix_rank(d)
d_inv = np.linalg.inv(d)
print(det, rank)
print(d_inv)
d1_inv = np.where(d_inv<0, 0, 1)
print(d1_inv)
E=np.where(d1_inv==0, C, B)
print(E)

размер массива B 16
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 7  8 10  9 14 13 15 10  5 10  8  6  6  1 14  5]
[ 7  8 10  9 14 13 15 10  5 10  8  6  6  1 14  5]
[[ 75  94 123 122]
 [154 180 236 222]
 [ 73 186 229 272]
 [ 92 132 352 352]]
-7662799.999999996 4
[[ 0.24512711 -0.0991648  -0.02658558 -0.00187399]
 [-0.19080754  0.08524821  0.02331785 -0.00565068]
 [-0.36185728  0.16212873  0.021115    0.00684867]
 [ 0.3693428  -0.16817873 -0.02291069 -0.00139897]]
[[1 0 0 0]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 0]]
[[  5   8  10   9]
 [ 14  50  86  10]
 [  5  86 149 212]
 [ 32   1  14   5]]
