In [7]:
import numpy as np
from numpy.linalg import norm
np.set_printoptions(precision=2, suppress=True)
a = np.matrix('1, 2, 0; 0, 0, 5; 3, -4, 2; 1, 6, 5; 0, 1, 0')
u, s, w = np.linalg.svd(a)
print(f'Матрица A:\n{a}')
# Транспонируем матрицу W
v = w.T
print(f'Матрица V:\n{v}')
# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
d = np.zeros_like(a, dtype=float)
d[np.diag_indices(min(a.shape))] = s
print(f'Матрица D:\n{d}')
print(f'Матрица U:\n{u}')
# Убедимся, что она действительно ортогональна
print(np.dot(u.T, u))

# Убедимся, что она действительно ортогональна
print(np.dot(v.T, v))
# Проведем проверку
print(np.dot(np.dot(u, d), v.T))
print(f'l1 евклидова норма:\n{norm(a, ord=2)}')
print(f'l1 Фробениуса норма:\n{norm(a, ord= None)}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]
Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]
Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
[[ 1.  0. -0.  0. -0.]
 [ 0.  1.  0.  0.  0.]
 [-0.  0.  1. -0. -0.]
 [ 0.  0. -0.  1. -0.]
 [-0.  0. -0. -0.  1.]]
[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]
[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]
l1 евклидова норма:
8.824868854820444
l1 Фробениуса норма:
11.045361017187261
