In [30]:
#Тема “Вычисления с помощью Numpy”
#Задание 1
import numpy as np
a = np.array([[1, 6],
             [2, 8],
             [3,1],
             [3, 10],
             [1, 7]])
mean_a = a.mean(axis=0)

print(a)
print("среднее значение признака: {}".format(a.mean(axis=0)))
print(mean_a)
print("Размерность a: {}".format(a.ndim))


#Задание 2
#Вычислите массив a_centered, отняв от значений массива “а”
# средние значения соответствующих признаков, содержащиеся
# в массиве mean_a. Вычисление должно производиться в одно
# действие. Получившийся массив должен иметь размер 5x2.

b = mean_a.reshape(1, 2)
print(b)
a_centered = a - b
print(a_centered)

#Задание 3
#Найдите скалярное произведение столбцов массива a_centered.
# В результате должна получиться величина a_centered_sp.
# Затем поделите a_centered_sp на N-1, где N - число наблюдений.
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
print(a_centered_sp)
n=a.shape[0]
c = a_centered_sp/(n-1)
print(c)
#Задание 4**
#В этом задании проверьте получившееся число, вычислив
# ковариацию еще одним способом - с помощью функции np.cov.
# В качестве аргумента m функция np.cov должна принимать
# транспонированный массив “a”. В получившейся ковариационной
# матрице (массив Numpy размером 2x2) искомое значение ковариации
# будет равно элементу в строке с индексом 0 и столбце с индексом 1.
a_t = np.transpose(a)
print(a_t)
print("матрица : {}".format(np.cov(a_t)))
print("Ковариантность a: {}".format(a_t_cov[0,1]))

[[ 1  6]
 [ 2  8]
 [ 3  1]
 [ 3 10]
 [ 1  7]]
среднее значение признака: [2.  6.4]
[2.  6.4]
Размерность a: 2
[[2.  6.4]]
[[-1.  -0.4]
 [ 0.   1.6]
 [ 1.  -5.4]
 [ 1.   3.6]
 [-1.   0.6]]
-2.0
-0.5
[[ 1  2  3  3  1]
 [ 6  8  1 10  7]]
матрица : [[ 1.  -0.5]
 [-0.5 11.3]]
Ковариантность a: -0.5


In [48]:
#Тема “Работа с данными в Pandas”
#Создайте датафрейм authors со столбцами author_id и author_name,
# в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов',
# 'Островский'].
import pandas as pd
import numpy as np
authors = pd.DataFrame({'author_id': [1, 2, 3],
'author_name': ['Тургенев', 'Чехов', 'Островский']})
columns = (['author_id', 'author_name'])
authors

books = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
'price':[450, 300, 350, 500, 450, 370, 290]},
columns=['author_id', 'book_title', 'price'])
books

authors_price = pd.merge(authors, books, on = 'author_id', how = 'outer')
authors_price

top5 = authors_price.nlargest(5, 'price')
top5

df_1 = authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns={'price':'min_price'})
df_2 = authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns={'price':'max_price'})
df_3 = authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns={'price':'mean_price'})
authors_stat = pd.concat([df_1, df_2, df_3], axis = 1)
authors_stat

df_4 = pd.DataFrame({'cover':['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']}, columns=['cover'])
authors_price = pd.concat([authors_price, df_4], axis = 1)
authors_price

book_info = pd.pivot_table(authors_price, values='price', index=['author_name'],
columns=['cover'], aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950