In [8]:
#1
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

boston = load_boston()
print(boston.keys())
data = boston["data"]
print(data.shape)
feature_names = boston["feature_names"]
print(feature_names[:10])
target = boston["target"]
print(target[:10])
x = pd.DataFrame(data, columns=feature_names)
print(x.head)
y = pd.DataFrame(target, columns=["price"])
print(y.info())
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)
lr = LinearRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
print(y_pred.shape)
check_test = pd.DataFrame({
 "y_test": y_test["price"],
 "y_pred": y_pred.flatten(),
})
print(check_test.head(10))
check_test["error"] = check_test["y_pred"] - check_test["y_test"]

print(check_test.head())
r2_score_1=r2_score(check_test["y_pred"], check_test["y_test"])
print(r2_score_1)

#2
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=1000, max_depth=12, random_state=42)
model.fit(x_train, y_train.values[:, 0])
y_pred = model.predict(x_test)
print(y_pred.shape)
check_test = pd.DataFrame({ "y_test": y_test["price"], "y_pred": y_pred.flatten()})
print(check_test.head(10))
r2_score_2=r2_score(check_test["y_pred"], check_test["y_test"])
print(r2_score_2)
if r2_score_1<r2_score_2:
    print(True)

#3
?RandomForestRegressor
# feature_importances_ : ndarray of shape (n_features,)
# The impurity-based feature importances.
# The higher, the more important the feature.
# The importance of a feature is computed as the (normalized) total reduction of the criterion brought by that feature.
# It is also known as the Gini importance.
print(model.feature_importances_)
print(model.feature_importances_.sum())
max_value_idx_1=model.feature_importances_.argmax()
print(max_value_idx_1)
#дальше не понимаю как и с чем сравнивать

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])
(506, 13)
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX']
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9]
<bound method NDFrame.head of         CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93 

In [13]:
#4
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
df = pd.read_csv('creditcard.csv')
print(df.head())
print(df["Class"].value_counts(normalize=True))
print(df.info())
print(df.isnull().astype(np.int).sum().astype(np.int))
print(df.head(10))
X = df.drop("Class", axis=1)
X.head()
y = df["Class"]
y.head()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100, stratify=y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
parameters = [{'n_estimators': [10, 15], 'max_features': np.arange(3, 5), 'max_depth': np.arange(4, 7)}]
clf = GridSearchCV(estimator=RandomForestClassifier(random_state=100), param_grid=parameters, scoring='roc_auc', cv=3)
clf.fit(X_train, y_train)
print(clf.best_params_)
y_pred_proba = clf.predict_proba(X_test)
print(y_pred_proba[:10])
y_pred_proba = y_pred_proba[:, 1]
print(y_pred_proba[:5])
print(roc_auc_score(y_test, y_pred_proba))

   Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28 

In [27]:
#доп задания
from sklearn.datasets import load_wine
data = load_wine()
print(data.keys())
print(type(data))
data_keys=data["feature_names"]
print(data_keys)
print(data.data)
print(data.data.shape)

for line in data.DESCR.split('\n'):
    print(line)
print(data["DESCR"])
print(np.unique(data["target"]).shape)
print(data["target_names"])
X = pd.DataFrame(data.data, columns=feature_names)
print(X.head())
print(X.info())
print(X.shape)
print(X.isnull().astype("int").sum())
X["target"]=data["target"].astype(np.int64)
print(X.info())
print(X.head)
print(X.corr())
X_corr=X.corr()
high_corr=X_corr["target"]
high_corr=high_corr[np.abs(high_corr)>0.5].drop("target", axis=0)
print(list(high_corr.index))
X=X.drop("target", axis=1)
print(X.head())
for i in high_corr:
    X[i+"_2"]=X[i]**2
print(X.head())
print(X.describe())


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])
<class 'sklearn.utils.Bunch'>
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
(178, 13)
.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Informatio