In [19]:
#метод Крамера
import numpy as np
def subst_col (matrix, column, index):
    resmatrix = []
    for i in range(0, len(matrix)):
        row=[]
        for j in range (len(matrix[i])):
            val = matrix[i][j]
            if j == index:
                val = column[i]
            row.append(val)
        resmatrix.append(row)
    return resmatrix

n = int(input("ввести ранг матрицы n ="))
a=np.random.randint(9,size=(n,n))
b=np.random.randint(9,size=(n))
det_a = np.linalg.det(a)
print(f'матрица а:\n{a}')
print(f'матрица а:\n{b}')
print(f'детерминант матрицы а:\n{det_a}')
if det_a != 0:
    for i in range(0, n):
        a_1=subst_col(a,b,i)
        print(f'матрица а_1:\n{a_1}')
        det_i = np.linalg.det(a_1)
        x=det_i/det_a
        print(x)


матрица а:
[[7 4 7]
 [6 8 7]
 [7 4 8]]
матрица а:
[8 4 5]
детерминант матрицы а:
31.999999999999986
матрица а_1:
[[8, 4, 7], [4, 8, 7], [5, 4, 8]]
4.125000000000001
матрица а_1:
[[7, 8, 7], [6, 4, 7], [7, 5, 8]]
0.031250000000000125
матрица а_1:
[[7, 4, 8], [6, 8, 4], [7, 4, 5]]
-3.000000000000001
